<a href="https://colab.research.google.com/github/aslidagar/TechnoHacks-Intern-/blob/main/Statistics(mean%2Cmedian%2Cmode).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Name : Lakshay Dagar
# Task - 2
Calculating summary statistics (mean, median,mode, standard deviation) for a dataset

In [2]:
#Importing Python Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import numpy as np

# Importing the cleaned dataset

In [3]:
df=pd.read_csv('/titanic cleaned data.csv')
df

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,32.204208,B96 B98,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,32.204208,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,32.204208,B96 B98,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,32.204208,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,32.204208,B96 B98,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,32.204208,B96 B98,S
821,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,32.204208,B42,S
822,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,32.204208,B96 B98,S
823,889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,32.204208,C148,C
824,890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,32.204208,B96 B98,Q

# Extracting The Shape Of The Datset

In [4]:
df.shape

(825, 13)

# Geting The Top 10 Rows Of The DataFrame

In [6]:
df.head(10)

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,32.204208,B96 B98,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,32.204208,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,32.204208,B96 B98,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,32.204208,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,32.204208,B96 B98,S
5,5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,32.204208,B96 B98,Q
6,6,7,0,1,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,32.204208,E46,S
7,8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.000000,0,2,347742,32.204208,B96 B98,S
8,9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,1,0,237736,32.204208,B96 B98,C
9,10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.000000,1,1,PP 9549,32.204208,G6,S

# Geting The Top 10 Rows From Bottom Of The DataFrame

In [7]:
df.tail

<bound method NDFrame.tail of      Unnamed: 0  PassengerId  Survived  Pclass  \
0             0            1         0       3
1             1            2         1       1
2             2            3         1       3
3             3            4         1       1
4             4            5         0       3
..          ...          ...       ...     ...
820         886          887         0       2
821         887          888         1       1
822         888          889         0       3
823         889          890         1       1
824         890          891         0       3

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000
2                               Heikkinen, Miss. Laina  female  26.000000
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000
4                             Allen, Mr. William Henry    male  35.000000
..                                                 ...     ...        ...
820                              Montvila, Rev. Juozas    male  27.000000
821                       Graham, Miss. Margaret Edith  female  19.000000
822           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118
823                              Behr, Mr. Karl Howell    male  26.000000
824                                Dooley, Mr. Patrick    male  32.000000

     SibSp  Parch            Ticket       Fare    Cabin Embarked
0        1      0         A/5 21171  32.204208  B96 B98        S
1        1      0          PC 17599  32.204208      C85        C
2        0      0  STON/O2. 3101282  32.204208  B96 B98        S
3        1      0            113803  32.204208     C123        S
4        0      0            373450  32.204208  B96 B98        S
..     ...    ...               ...        ...      ...      ...
820      0      0            211536  32.204208  B96 B98        S
821      0      0            112053  32.204208      B42        S
822      1      2        W./C. 6607  32.204208  B96 B98        S
823      0      0            111369  32.204208     C148        C
824      0      0            370376  32.204208  B96 B98        Q

[825 rows x 13 columns]>

# Getting the information about all columns in the DataFrame.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   825 non-null    int64
 1   PassengerId  825 non-null    int64
 2   Survived     825 non-null    int64
 3   Pclass       825 non-null    int64
 4   Name         825 non-null    object
 5   Sex          825 non-null    object
 6   Age          825 non-null    float64
 7   SibSp        825 non-null    int64
 8   Parch        825 non-null    int64
 9   Ticket       825 non-null    object
 10  Fare         825 non-null    float64
 11  Cabin        825 non-null    object
 12  Embarked     824 non-null    object
dtypes: float64(2), int64(6), object(5)
memory usage: 83.9+ KB

In [13]:
df.dtypes

Unnamed: 0       int64
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

# Counting the number of missing values in each column of the DataFrame.

In [14]:
df.isnull().sum()

Unnamed: 0     0
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       1
dtype: int64

In [15]:
df["Cabin"].mode()

0    B96 B98
Name: Cabin, dtype: object

In [16]:
df["Cabin"].fillna(df["Cabin"].mode()[0],inplace=True)

In [17]:
df.isnull().sum()

Unnamed: 0     0
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       1
dtype: int64

# Getting all column names in the DataFrame.

In [18]:
df.columns

Index(['Unnamed: 0', 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

# Count of the DataFrame

In [19]:
df.count()

Unnamed: 0     825
PassengerId    825
Survived       825
Pclass         825
Name           825
Sex            825
Age            825
SibSp          825
Parch          825
Ticket         825
Fare           825
Cabin          825
Embarked       824
dtype: int64

#Mean of the DataFrame

In [20]:
df.mean(numeric_only='True')

Unnamed: 0     446.369697
PassengerId    447.369697
Survived         0.380606
Pclass           2.341818
Age             28.879689
SibSp            0.507879
Parch            0.357576
Fare            32.204208
dtype: float64

#Median of the DataFrame

In [21]:
df.median(numeric_only='True')

Unnamed: 0     444.000000
PassengerId    445.000000
Survived         0.000000
Pclass           3.000000
Age             29.699118
SibSp            0.000000
Parch            0.000000
Fare            32.204208
dtype: float64

#Mode of the DataFrame

In [22]:
df.mode()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0.0,3.0,"Abbing, Mr. Anthony",male,29.699118,0.0,0.0,1601,32.204208,B96 B98,S
1,1,2,NaN,NaN,"Abbott, Mr. Rossmore Edward",NaN,NaN,NaN,NaN,CA. 2343,NaN,NaN,NaN
2,2,3,NaN,NaN,"Abbott, Mrs. Stanton (Rosa Hunt)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,4,NaN,NaN,"Abelson, Mr. Samuel",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,5,NaN,NaN,"Abelson, Mrs. Samuel (Hannah Wizosky)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,886,887,NaN,NaN,"de Mulder, Mr. Theodore",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821,887,888,NaN,NaN,"de Pelsmaeker, Mr. Alfons",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
822,888,889,NaN,NaN,"del Carlo, Mr. Sebastiano",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
823,889,890,NaN,NaN,"van Billiard, Mr. Austin Blyler",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
824,890,891,NaN,NaN,"van Melkebeke, Mr. Philemon",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#Standard Deviation of the DataFrame

In [23]:
df_std=df.std(numeric_only='True')
df_std

Unnamed: 0     2.570889e+02
PassengerId    2.570889e+02
Survived       4.858304e-01
Pclass         8.240965e-01
Age            1.018271e+01
SibSp          1.090670e+00
Parch          7.985995e-01
Fare           7.109738e-15
dtype: float64

#Statistical Summary Of Data Frame

In [24]:
df.describe()

,Unnamed: 0,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,825.000000,825.000000,825.000000,825.000000,825.000000,825.000000,825.000000,8.250000e+02
mean,446.369697,447.369697,0.380606,2.341818,28.879689,0.507879,0.357576,3.220421e+01
std,257.088865,257.088865,0.485830,0.824096,10.182710,1.090670,0.798599,7.109738e-15
min,0.000000,1.000000,0.000000,1.000000,3.000000,0.000000,0.000000,3.220421e+01
25%,225.000000,226.000000,0.000000,2.000000,22.000000,0.000000,0.000000,3.220421e+01
50%,444.000000,445.000000,0.000000,3.000000,29.699118,0.000000,0.000000,3.220421e+01
75%,670.000000,671.000000,1.000000,3.000000,34.000000,1.000000,0.000000,3.220421e+01
max,890.000000,891.000000,1.000000,3.000000,54.000000,8.000000,6.000000,3.220421e+01

In [25]:
df.describe(include='all')

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,825.000000,825.000000,825.000000,825.000000,825,825,825.000000,825.000000,825.000000,825,8.250000e+02,825,824
unique,NaN,NaN,NaN,NaN,825,2,NaN,NaN,NaN,647,NaN,128,3
top,NaN,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,CA. 2343,NaN,B96 B98,S
freq,NaN,NaN,NaN,NaN,1,531,NaN,NaN,NaN,7,NaN,653,599
mean,446.369697,447.369697,0.380606,2.341818,NaN,NaN,28.879689,0.507879,0.357576,NaN,3.220421e+01,NaN,NaN
std,257.088865,257.088865,0.485830,0.824096,NaN,NaN,10.182710,1.090670,0.798599,NaN,7.109738e-15,NaN,NaN
min,0.000000,1.000000,0.000000,1.000000,NaN,NaN,3.000000,0.000000,0.000000,NaN,3.220421e+01,NaN,NaN
25%,225.000000,226.000000,0.000000,2.000000,NaN,NaN,22.000000,0.000000,0.000000,NaN,3.220421e+01,NaN,NaN
50%,444.000000,445.000000,0.000000,3.000000,NaN,NaN,29.699118,0.000000,0.000000,NaN,3.220421e+01,NaN,NaN
75%,670.000000,671.000000,1.000000,3.000000,NaN,NaN,34.000000,1.000000,0.000000,NaN,3.220421e+01,NaN,NaN
max,890.000000,891.000000,1.000000,3.000000,NaN,NaN,54.000000,8.000000,6.000000,NaN,3.220421e+01,NaN,NaN

#Calculate the correlation between numeric columns in a DataFrame.

In [27]:
df.corr(numeric_only='True')

,Unnamed: 0,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Unnamed: 0,1.000000,1.000000,-0.018151,-0.034032,0.048444,-0.053075,-0.006142,NaN
PassengerId,1.000000,1.000000,-0.018151,-0.034032,0.048444,-0.053075,-0.006142,NaN
Survived,-0.018151,-0.018151,1.000000,-0.367774,-0.027320,-0.030860,0.074199,NaN
Pclass,-0.034032,-0.034032,-0.367774,1.000000,-0.286128,0.057760,0.018742,NaN
Age,0.048444,0.048444,-0.027320,-0.286128,1.000000,-0.182124,-0.131052,NaN
SibSp,-0.053075,-0.053075,-0.030860,0.057760,-0.182124,1.000000,0.408487,NaN
Parch,-0.006142,-0.006142,0.074199,0.018742,-0.131052,0.408487,1.000000,NaN
Fare,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#Creates a separate groups for each survival outcome (survived and not survived).

In [28]:
### Overview(Survived vs non survied)
survived_summary= df.groupby("Survived")
survived_summary.mean(numeric_only='True').reset_index()

,Survived,Unnamed: 0,PassengerId,Pclass,Age,SibSp,Parch,Fare
0,0,450.025440,451.025440,2.579256,29.097632,0.534247,0.311155,32.204208
1,1,440.420382,441.420382,1.955414,28.525013,0.464968,0.433121,32.204208

# Creates a separate groups for each survival outcome (Male & Female).

In [29]:
survived_summary = df.groupby("Sex")
survived_summary.mean(numeric_only='True').reset_index()

,Sex,Unnamed: 0,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
0,female,431.965986,432.965986,0.741497,2.166667,28.076712,0.687075,0.639456,32.204208
1,male,454.344633,455.344633,0.180791,2.438795,29.324276,0.408663,0.201507,32.204208